export const actionTypes={
    FETCH_POSTS:"FETCH_POSTS",
    ADD_POST:"ADD_POST",
    UPDATE_POST:"UPDATE_POST",
    DELETE_POST:"DELETE_POST",
    LIKE_POST:"LIKE_POST",
    AUTH:"AUTH",
    LOGOUT:"LOGOUT"
    
}